name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with coverage
      run: dotnet test --collect:"XPlat Code Coverage" --no-build

    - name: Print code coverage
      run: coverage=$(find ./**/TestResults -name 'coverage.cobertura.xml' | head -n1) && awk '/<coverage[[:space:]]/ { match($0, /<coverage[^>]*>/); if (RSTART) print substr($0, RSTART, RLENGTH) }'  "$coverage"
